#!/usr/bin/env php
<?php
if (file_exists(__DIR__.'/../../autoload.php')) {
    /** @noinspection PhpIncludeInspection */
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}
$app = new Symfony\Component\Console\Application('objective-wp Installer', '0.0.1');
$app->add(new ObjectiveWP\Console\InitCommand);
$app->add(new ObjectiveWP\Console\SetOrganizationCommand);
/** @noinspection PhpUnhandledExceptionInspection */
$app->run();